name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "trigger.sh"
        target: "trigger"
        strip_components: 1
        
        
    - name: executing remote ssh commands using passwo$rd
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }} 
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          chmod +x $HOME/trigger/trigger.sh
          /bin/bash $HOME/trigger/trigger.sh
